languageCode = "en-us"
title = "Yara"
baseurl = "http://example.org/"
theme = "aerial"

[params]
  name = "Yara  "
  about = "diabetes prediction" 
  copyright = "Untitled"
  #Disable the scrolling background by entering any string for bg_scroll. Enable by leaving bg_scroll empty.
  bg_scroll = ""
  favicon = "favicon.ico"
blog="diabetes prediction"


[[params.social]]
  medium = "Facebook"
  icon = "facebook"
  link = "https://www.facebook.com/yara.metwally.146"


[[params.social]]
  medium = "Github"
  icon = "github"
  link = "https://github.com/yara7"

[[params.social]]
  medium = "Email"
  icon = "envelope-o"
  link = ""
